name: "Page Speed Insights"
description: "Utilize Google's Page Speed Insights to audit your application"
branding:
  icon: "clock"
  color: "blue"
inputs:
  url:
    description: "The URL to run the check against"
    required: true
runs:
  using: "node12"
  main: "index.js"
