on: [push]

jobs:
  run_psi:
    runs-on: ubuntu-latest
    name: Running Page Speed Insights
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Running Page Speed Insights
        uses: ./ # Uses an action in the root directory
        id: psi
        with:
          url: "https://google.com"
